from timestamp import MultiPartTimestamp
from service import Totaler
import dataclasses
import random
from copy import deepcopy
from typing import List, Tuple, Any

DEBUG = False


@dataclasses.dataclass
class ProcedureCall:
    name: str
    args: dict


@dataclasses.dataclass
class OperationInfo:
    pass
    # Invocation ID
    # cid: Any
    # Actual timestamp, for timeouts
    # time: datetime.datetime


@dataclasses.dataclass
class QueryResult:
    val: Totaler
    ts: MultiPartTimestamp


@dataclasses.dataclass
class AckInfo(OperationInfo):
    pass


@dataclasses.dataclass
class UpdateInfo(OperationInfo):
    prev: MultiPartTimestamp
    op: ProcedureCall
    front_end_id: int


@dataclasses.dataclass
class QueryInfo(OperationInfo):
    prev: MultiPartTimestamp
    front_end_id: int


@dataclasses.dataclass
class GossipInfo:
    src: int
    src_ts: MultiPartTimestamp
    records: List["Record"]


@dataclasses.dataclass
class Record:
    # About the operation
    msg: OperationInfo
    # The node that originated the record
    rnode: int
    # Timestamp at rnode when the record was created
    ts: MultiPartTimestamp


class QueueFullException(Exception):
    pass


class GossipQueue:
    def __init__(self, capacity: int = 5000) -> None:
        self._queue: List[Record] = []
        self.capacity = capacity

    def __len__(self):
        return len(self._queue)

    @property
    def size(self):
        return len(self._queue)

    def push(self, msg: GossipInfo) -> None:
        if self.size >= self.capacity:
            raise QueueFullException("Queue is full")
        self._queue.append(msg)

    def pop(self) -> GossipInfo:
        return self._queue.pop()

    def lpop(self) -> GossipInfo:
        return self._queue.pop(0)


class UpdateQueue:
    def __init__(self, capacity: int = 500) -> None:
        self._queue: List[Tuple] = []
        self.capacity = capacity

    def __len__(self):
        return len(self._queue)

    @property
    def size(self):
        return len(self._queue)

    def push(self, u: UpdateInfo, uid: int = -1) -> None:
        """
        Push onto queue.

        The ``uid`` argument should only be set if we're
        re-adding an update to the queue. Otherwise, the uid
        will be generated by this function.
        """
        if self.size >= self.capacity:
            raise QueueFullException("Queue is full")
        if uid == -1:
            uid = random.randint(0, 1000000)
        self._queue.append((uid, u))
        return uid

    def pop(self) -> UpdateInfo:
        return self._queue.pop()

    def lpop(self) -> UpdateInfo:
        return self._queue.pop(0)


class QueryQueue:
    def __init__(self, capacity: int = 500) -> None:
        self._queue: List[Tuple[int, MultiPartTimestamp]] = []
        self.capacity = capacity

    def __len__(self):
        return len(self._queue)

    @property
    def size(self):
        return len(self._queue)

    def push(self, q: QueryInfo, uid: int = -1) -> int:
        if self.size >= self.capacity:
            raise QueueFullException("Queue is full")
        if uid == -1:
            uid = random.randint(0, 1000000)
        self._queue.append((uid, q))
        return uid

    def pop(self) -> Tuple[int, QueryInfo]:
        return self._queue.pop()


@dataclasses.dataclass
class Node:
    # Identifies the node
    id: int
    log: List[Record]
    # Maintains knowledge of what updates this node has seen
    rep_ts: MultiPartTimestamp
    # Value that is updated
    val: Totaler
    # Maintains knowledge of updates that have actually been applied
    val_ts: MultiPartTimestamp
    # List of CIDs for deduplication purposes
    inval: List[Any]
    # List of mpts's received from other nodes, used to evaluate whether
    # an update is "known everywhere"
    ts_table: List[MultiPartTimestamp]
    gossip_queue: GossipQueue
    update_queue: UpdateQueue
    query_queue: QueryQueue
    # For routing gossip/broadcast messages
    other_nodes: List["Node"] = dataclasses.field(default_factory=list)
    # Storage for results that front ends are looking for
    query_results: List[Tuple[int, Totaler]] = dataclasses.field(default_factory=list)
    update_results: List[Tuple[int, MultiPartTimestamp]] = dataclasses.field(
        default_factory=list
    )
    stats: dict = dataclasses.field(default_factory=dict)

    def __post_init__(self):
        self.stats = {
            "updates": 0,
            "gossip_messages_processed": 0,
            "gossip_updates_processed": 0,
            "queries": 0,
        }

    def _log_message(self, msg: str) -> None:
        global DEBUG
        if DEBUG:
            print(f"Node {self.id} :: {msg}")

    def summarize(self) -> None:
        print(f"Node ({self.id})")
        print(f"  Log records: {len(self.log)}")
        print("  First 5 log records:")
        records_to_print = self.log[:5] if len(self.log) >= 5 else self.log
        for r in records_to_print:
            print("    " + str(r))

        print(f"  Replica TS: {self.rep_ts}")
        print(f"  Value: {self.val}")
        print(f"  Value TS: {self.val_ts}")
        print(f"  TS Table: {self.ts_table}")
        print(f"  Gossip queue length: {len(self.gossip_queue)}")
        print(f"  Update queue length: {len(self.update_queue)}")
        print(f"  Query queue length: {len(self.query_queue)}")
        print(f"  Query results length: {len(self.query_results)}")
        print(f"  Update results length: {len(self.update_results)}")
        print(f"  Stats: {self.stats}")

    def clear_update_queue(self) -> None:
        self._log_message(f"Clearing update queue ({len(self.update_queue)})")
        # Set to an initial value that will never match len(update_queue)
        prev_uq_len = -1
        while True:
            if len(self.update_queue) == 0:
                self._log_message("No more updates to process")
                break
            # Prevent infinite loops
            if len(self.update_queue) == prev_uq_len:
                self._log_message("Preventing an infinite loop!")
                break
            prev_uq_len = len(self.update_queue)
            op_map = {
                "add": self.val.add,
                "subtract": self.val.subtract,
                "incr": self.val.incr,
                "decr": self.val.decr,
            }
            uid, update_info = self.update_queue.lpop()
            # If update is not ready to be applied, put it back in the queue
            self._log_message(
                f"Update: (fid: {update_info.front_end_id}, nid: {self.id}) f.prev: {update_info.prev} vs val.prev {self.val_ts}"
            )

            # Increment self timestamp
            self.rep_ts.incr(self.id)
            self.ts_table[self.id] = self.rep_ts.copy()

            # Update u.prev's timestamp for this node using self.rep_ts.get(self.id)
            current_rep_ts = self.rep_ts.get(self.id)
            rec_ts = update_info.prev.copy()
            rec_ts.set(self.id, current_rep_ts)

            # Create a record and save it in the log
            self.log.append(Record(msg=update_info, rnode=self.id, ts=rec_ts))

            # Decide whether to apply update or not
            if not update_info.prev <= self.val_ts:
                self._log_message(
                    f"Update can't be applied! Need more gossip {update_info.prev} <= {self.val_ts}"
                )
            else:
                self._log_message(f"Applying update message {update_info}")
                # Apply to val
                op = op_map[update_info.op.name]
                kwargs = update_info.op.args or {}
                op(**kwargs)
                # Set the timestamp for the value by merging u.prev and val_ts
                self.val_ts = self.val_ts.merge(rec_ts)

            # Finally, add the new timestamp to the update result list
            self.update_results.append((uid, rec_ts.copy()))
            self.stats["updates"] += 1

    def ack_update_result(self, id: int) -> None:
        self.update_results = [x for x in self.update_results if x[0] != id]

    def clear_query_queue(self) -> None:
        self._log_message(f"Clearing query queue ({len(self.query_queue)})")
        prev_qq_len = -1
        while True:
            if len(self.query_queue) == 0:
                self._log_message("No more queries to return")
                break
            # Prevent infinite loops
            if len(self.query_queue) == prev_qq_len:
                break
            prev_qq_len = len(self.query_queue)

            # Remove all queue elements and write val to results
            uid, query_info = self.query_queue.pop()
            self._log_message(
                f"Query: (fid: {query_info.front_end_id} nid: {self.id}) prev ts: {query_info.prev} local ts: {self.val_ts}"
            )
            if query_info.prev <= self.val_ts:
                self.query_results.append(
                    (uid, QueryResult(val=self.val.copy(), ts=self.val_ts.copy()))
                )
                self.stats["queries"] += 1
            else:
                self._log_message("Sorry! I can't process this query right now")
                self.query_queue.push(q=query_info, uid=uid)

    def ack_query_result(self, id: int) -> None:
        self.query_results = [x for x in self.query_results if x[0] != id]

    def send_gossip(self) -> None:
        self._log_message("Broadcasting gossip")
        if not self.other_nodes:
            return
        # Make a gossip message
        log_messages = [x for x in self.log if x.rnode == self.id]
        msg = GossipInfo(
            src=self.id, src_ts=self.rep_ts.copy(), records=deepcopy(log_messages)
        )
        # Send all of this node's log records to all other nodes
        for n in self.other_nodes:
            n.gossip_queue.push(deepcopy(msg))

    def clear_gossip_queue(self) -> None:
        self._log_message(f"Clearing gossip queue ({len(self.gossip_queue)})")
        op_map = {
            "add": self.val.add,
            "subtract": self.val.subtract,
            "incr": self.val.incr,
            "decr": self.val.decr,
        }
        while True:
            self._log_message(
                f"Clearing gossip queue, my timestamp is now {self.rep_ts}"
            )
            if len(self.gossip_queue) == 0:
                self._log_message("No more gossip messages")
                break
            msg = self.gossip_queue.lpop()

            if msg.src_ts <= self.ts_table[msg.src]:
                self._log_message(
                    f"Discarding gossip message, already have these updates ({msg.src_ts} <= {self.ts_table[msg.src]})"
                )
                continue

            if msg.src == self.id:
                continue

            # Find new log records
            new_records = [x for x in msg.records if not (x.ts <= self.rep_ts)]
            old_records = [x for x in msg.records if x.ts <= self.rep_ts]
            self._log_message(
                f"Found {len(new_records)} new records, {len(old_records)} old records -- message timestamp {msg.src_ts}"
            )
            self.log.extend(deepcopy(new_records))

            # Merge timestamp into rep_ts
            self.rep_ts = self.rep_ts.merge(msg.src_ts)
            self.ts_table[self.id] = self.rep_ts.copy()

            # Update ts_table
            self.ts_table[msg.src] = msg.src_ts.copy()

            self.stats["gossip_messages_processed"] += 1

            # For each log record, apply the transformation
            # TODO: make this a packaged operation
            for r in new_records:
                umsg = r.msg
                op = op_map[umsg.op.name]
                kwargs = umsg.op.args or {}
                op(**kwargs)
                self._log_message(
                    f"Merging {self.val_ts} with {r.ts} -> {self.val_ts.merge(r.ts)}"
                )
                self.val_ts = self.val_ts.merge(r.ts)
                self.stats["gossip_updates_processed"] += 1

    def trim_log(self) -> int:
        """Trim log and report on number of entries removed"""
        self._log_message(f"Trimming log ({len(self.log)})")
        to_remove = []
        for i, r in enumerate(self.log):
            # This node can be confident that all other nodes have this
            # record already if it's received timestamps from them at
            # at least as late as the record's timestamp.
            isknown = all(
                [
                    self.ts_table[j.id].get(r.rnode) >= r.ts.get(r.rnode)
                    for j in self.other_nodes
                ]
            )
            if not isknown:
                continue
            to_remove.append(i)
        if to_remove:
            self._log_message(f"Removing {len(to_remove)} log records from log!")
        for i in reversed(to_remove):
            self.log.pop(i)
        return len(to_remove)

    def clean_log(self) -> None:
        """
        Go through log and apply any messages that have not yet been applied that can be applied.

        This is not well spec'd in the original paper, so I'm going to do my
        best to follow their logic.
        """
        if self.val_ts == self.rep_ts:
            return
        assert self.val_ts < self.rep_ts, "val_ts not less than or equal to rep_ts"

        # If r.prev <= self.rep_ts, then the message will already have been applied
        comp = [
            r
            for r in self.log
            if isinstance(r.msg, UpdateInfo) and r.msg.prev <= self.rep_ts
        ]

        # Sort comp
        # The paper recommends selecting a record r from comp such that there
        # exists no other record r_other such that r_other.ts <= r.op.prev
        # We can sort such that when comparing A and B, A is earlier than B if
        # A.ts <= B.prev.
        # Really not sure what an efficient way of doing this is. To the dumb
        # way, then!
        if len(comp) == 0:
            self._log_message("Did not find any messages in log that haven't yet been applied")
            return

        op_map = {
            "add": self.val.add,
            "subtract": self.val.subtract,
            "incr": self.val.incr,
            "decr": self.val.decr,
        }
        self._log_message(f"Found {len(comp)} messages in log to apply")
        while True:
            to_apply = None
            for r in comp:
                nopes = [s for s in comp if s != r and s.ts <= r.msg.prev]
                if not nopes:
                    to_apply = r
                    break
            if not to_apply:
                self._log_message("No more messages in log can be applied")
                return
            # Remove from comp
            comp = [x for x in comp if x != r]
            self._log_message("Got one! Found a log message that needs to be applied")
            # Apply to val
            op = op_map[r.msg.op.name]
            kwargs = r.msg.op.args or {}
            op(**kwargs)
            self.val_ts = self.val_ts.merge(r.msg.prev)
            self.stats["updates"] += 1


class FrontEnd:
    def __init__(self, id: int):
        self.id = id
        self.preferred_node = None
        self.prev = None
        self.nodes = dataclasses.field(default_factory=list)
        self.n_nodes = -1
        # Values seen so far (after successful polling)
        self.seen_vals = []
        # A UID to poll self.preferred_node for a query result
        self.query_poll_id = None
        # A UID to poll self.preferred_node for an update result
        self.update_poll_id = None
        # Current number of poll attempts
        self.poll_attempts = 0
        # Max attempts before giving up on a query
        self.max_poll_attempts = 5
        self.stats = {
            "updates": 0,
            "update_completes": 0,
            "query_starts": 0,
            "query_completes": 0,
            "failed_polls": 0,
        }

    @property
    def blocked_on_val(self) -> bool:
        return self.query_poll_id is not None

    @property
    def blocked_on_update(self) -> bool:
        return self.update_poll_id is not None

    @property
    def last_seen_val(self) -> Totaler:
        return self.seen_vals[-1] if self.seen_vals else None

    def _log_message(self, msg: str) -> None:
        global DEBUG
        if DEBUG:
            print(f"Front end {self.id} :: {msg}")

    def summarize(self) -> None:
        print(f"FrontEnd ({self.id})")
        print(f"  Preferred node: {self.preferred_node.id}")
        print(f"  Prev: {self.prev}")
        print(f"  Is blocked on query: {self.blocked_on_val}")
        print(f"  Is blocked on update: {self.blocked_on_update}")
        print(f"  Last received value: {self.last_seen_val}")
        print(f"  Seen vals: {self.seen_vals}")
        print(f"  Stats: {self.stats}")

    def choose_node(self) -> None:
        self.n_nodes = len(self.nodes)
        self.prev = MultiPartTimestamp([0] * self.n_nodes)
        chosen_node = random.randint(0, len(self.nodes) - 1)
        self._log_message(f"Choosing node to communicate with: {chosen_node}")
        self.preferred_node = nodes[chosen_node]

    def choose_new_node(self) -> None:
        chosen_node = random.randint(0, len(self.nodes) - 1)
        self._log_message(f"Choosing new node to communicate with: {chosen_node}")
        self.preferred_node = self.nodes[chosen_node]

    def update_val(self) -> bool:
        possible_calls = [
            ProcedureCall(name="incr", args={}),
            ProcedureCall(name="decr", args={}),
            ProcedureCall(name="add", args={"other": 5}),
            ProcedureCall(name="subtract", args={"other": 3}),
            # Poor man's weighting
            None,
            None,
        ]
        chosen_call = possible_calls[random.randint(0, len(possible_calls) - 1)]

        if not chosen_call:
            self._log_message("Skipping update")
            return False

        self._log_message(f"Running update {chosen_call}")
        self.update_poll_id = self.preferred_node.update_queue.push(
            UpdateInfo(prev=self.prev.copy(), op=chosen_call, front_end_id=self.id)
        )
        self.stats["updates"] += 1
        return True

    def poll_for_update(self) -> bool:
        self._log_message("Polling for update result")
        self.poll_attempts += 1
        if self.poll_attempts > self.max_poll_attempts:
            self.stats["failed_polls"] += 1
            self._clear_poll_state()
            return False

        for id, ts in self.preferred_node.update_results:
            if self.update_poll_id == id:
                self.preferred_node.ack_update_result(self.update_poll_id)
                self.stats["update_completes"] += 1
                self._clear_poll_state()
                self.prev = ts
                return True
        return False

    def query_val(self) -> None:
        self._log_message("Running query")
        self.stats["query_starts"] += 1
        self.query_poll_id = self.preferred_node.query_queue.push(
            QueryInfo(prev=self.prev, front_end_id=self.id)
        )

    def poll_for_val(self) -> bool:
        self._log_message("Polling for query result")
        self.poll_attempts += 1
        if self.poll_attempts > self.max_poll_attempts:
            self._log_message("Failed to poll for query result")
            self.stats["failed_polls"] += 1
            self._clear_poll_state()
            return False

        for id, qres in self.preferred_node.query_results:
            if self.query_poll_id == id:
                self.seen_vals.append(deepcopy(qres.val))
                self._log_message(f"Received value of query: {qres.val}")
                self.prev = qres.ts.copy()
                self.preferred_node.ack_query_result(self.query_poll_id)
                self.stats["query_completes"] += 1
                self._clear_poll_state()
                return True
        return False

    def _clear_poll_state(self) -> None:
        self.query_poll_id = None
        self.update_poll_id = None
        self.poll_attempts = 0


class Cluster:
    def __init__(self, nodes: List[Node], front_ends: List[FrontEnd]) -> None:
        self.t = 0
        self.nodes = nodes
        self.front_ends = front_ends
        self.stats = {
            "updates": 0,
        }
        for fe in self.front_ends:
            fe.choose_node()

    def summarize(self) -> None:
        n_nodes = len(self.nodes)
        n_fe = len(self.front_ends)
        print()
        print("======================")
        print("Summary")
        print(f"  Nodes: {n_nodes}")
        print(f"  Front ends: {n_fe}")
        print(f"  Current time: {self.t}")
        print(f"  Stats: {self.stats}")
        print("--------------------------")
        for fe in self.front_ends:
            fe.summarize()
        print("--------------------------")
        for node in self.nodes:
            node.summarize()
        print("======================")

    def run(self, n_ticks):
        for i in range(n_ticks):
            self.t = i
            for fe in self.front_ends:
                if fe.blocked_on_val:
                    fe.poll_for_val()
                elif fe.blocked_on_update:
                    fe.poll_for_update()
                else:
                    if fe.update_val():
                        self.stats["updates"] += 1
                    else:
                        fe.choose_new_node()
                        fe.query_val()
            for be in self.nodes:
                be.clear_gossip_queue()
                be.clean_log()
                be.clear_update_queue()
                be.clear_query_queue()
                be.send_gossip()
                be.trim_log()

        # Exchange gossip and try to get to consistency
        for be in self.nodes:
            be.send_gossip()
        for be in self.nodes:
            be.clear_gossip_queue()
            be.trim_log()
        for be in self.nodes:
            be.send_gossip()
        for be in self.nodes:
            be.clear_gossip_queue()
            be.trim_log()


# Runtime stuff ------------------------------------------------------


def _generate_nodes(n: int):
    nodes = []
    for i in range(n):
        nodes.append(
            Node(
                id=i,
                log=[],
                rep_ts=MultiPartTimestamp([0] * n),
                val=Totaler(),
                val_ts=MultiPartTimestamp([0] * n),
                inval=[],
                ts_table=[MultiPartTimestamp([0] * n) for _ in range(n)],
                gossip_queue=GossipQueue(),
                update_queue=UpdateQueue(),
                query_queue=QueryQueue(),
            )
        )
    return nodes


def _generate_front_ends(n: int):
    fes = []
    for i in range(n):
        fes.append(FrontEnd(id=i))
    return fes


if __name__ == "__main__":
    nodes = _generate_nodes(4)
    front_ends = _generate_front_ends(10)
    # Tell FEs and nodes about other nodes
    for fe in front_ends:
        fe.nodes = nodes
    for node in nodes:
        id = node.id
        node.other_nodes = [x for x in nodes if x.id != id]
    cluster = Cluster(nodes=nodes, front_ends=front_ends)
    cluster.run(100)
    cluster.summarize()
